### ISSUE TITLE
Plugin.Connectivity.CrossConnectivity.Current.IsConnected is giving true while its off

### ISSUE THREAD

**Issue by Duraiamuthan** [jamesmontemagno/ConnectivityPlugin#100]
My phone is connected with internet via wifi ,sometimes when wifi is off also, _IsConnected_ returns  true

## Bug Information
Version Number of Plugin:2.3.0
Device Tested On: Microsoft Lumia 650
Simulator Tested On: Mobile Emulator 10.0.10240.WVGA 4inch 512 MB
Version of VS: Visual studio 2017
Version of Xamarin: 4.6.3.4
Versions of other things you are using:
I am using windows 10(Build 10 10240)
I am using this in my View models Portable Class Library in which I use MVVMlight 5.3.0.0

### Steps to reproduce the Behavior
the bug seems to be random when wifi is turned on and off and then suddenly this problem occurs once the problem occurs it wouldn't go away till the device is restarted

### Expected Behavior
 _IsConnected_ has to return false when there is no internet  at any given time

### Actual Behavior
 _IsConnected_  gives true while the internet connection is off

### Code snippet
if (Plugin.Connectivity.CrossConnectivity.Current.IsConnected){

}

**Comment by rodrigojuarez** [comment]
I have the same problem with my iPad mini 4, with airplane mode on and wifi off
It's a wifi only model
Using Xam.Plugin.Connectivity 3.0.2
Xamarin 4.6.3.4
Xamarin.iOS 10.12.3.3

**Comment by prashantvc** [comment]
@Duraiamuthan @rodrigojuarez Is your device connected to the Mac/Windows over USB? Could you read the _IsConnected_ value when device is not connected to a PC/Mac

**Comment by Duraiamuthan** [comment]
@prashantvc I was able to reproduce this issue once without USB connected to my Windows and I had to restart the mobile to get things right then there after I wasn't able to reproduce this issue for some time but may be if I try some more times it might get reproduced.just out of curiosity why would it matter if its connected with USB or not ?

**Comment by rodrigojuarez** [comment]
Same as @Duraiamuthan my device was connected with an USB cable, but then I can reproduce one time with the device disconnected from the mac computer

**Comment by prashantvc** [comment]
Thanks for the details

> just out of curiosity why would it matter if its connected with USB or not ?

I have noticed, sometime, Mac shares internet connection to the connected device when debugging

**Comment by jamesmontemagno** [comment]
Did you try the latest pre-release of this. It has already been fixed for certain devices.

https://github.com/jamesmontemagno/ConnectivityPlugin/issues/96

**Comment by rodrigojuarez** [comment]
So, this should be working in the pre-release version?

**Comment by jamesmontemagno** [comment]
will check again as that was related to Android not iOS... additionally looks like the original was on UWP in general.

Could you just run the sample in the test directory and just test the code and see what is going on on your specific device.

**Comment by rodrigojuarez** [comment]
Are you talking about the sample app?
That was the result with my wifi off and airplane mode on, running from the computer with my iPad connected with usb cable

<img width="427" alt="img-0003" src="https://user-images.githubusercontent.com/788727/30649258-2c9c47e0-9df6-11e7-832f-76f3e8134a47.PNG">

Or can you point me to the code I should be running?

**Comment by jamesmontemagno** [comment]
When you run the tests project: https://github.com/jamesmontemagno/ConnectivityPlugin/tree/master/tests

You can step through the code and see what is happening.

**Comment by paragcjoshi** [comment]
I have the same issue. Scenario:
1) We use the plugin for an iOS and UWP app.
2) Prior to logging in we call CrossConnectivity.Current.IsConnected

Failure scenario (iOS and UWP but below test was done on iOS):
1) Wifi is connected but router WAN cable unplugged 
2) Wifi is connected but using Developer - Network Conditioner to indicated 100 % packet loss

In both the two scenarios above, we get IsConnected as true.

I checked using the latest beta 139 release

Files attached below:


![unadjustednonraw_thumb_55](https://user-images.githubusercontent.com/1848118/30979260-2b76bf02-a44b-11e7-898b-bcc776d04bf0.jpg)
![unadjustednonraw_thumb_56](https://user-images.githubusercontent.com/1848118/30979262-2b88d37c-a44b-11e7-89a0-b1ce1b76ed7e.jpg)

**Comment by jamesmontemagno** [comment]
It doesn't check for packet loss. You would want to use IsRemoteReachable. It is only saying you are connected to an endpoint.

Closing as i pushed out 3.0.3 with several changed.

**Comment by Duraiamuthan** [comment]
@jamesmontemagno @prashantvc I tried the latest plugin in UWP it's working fine and I couldn't reproduce the bug

**Comment by Duraiamuthan** [comment]
I tried the latest plugin in Lumia 640 LTE it works fine but when I tried the same in Lumia 650 it doesn't work at all (when the wifi is off .. it says it has internet connectivity on

**Comment by Duraiamuthan** [comment]
If you could re-open the issue, it'd be great

**Comment by HelenMamalaki** [comment]
@jamesmontemagno This is still a problem in v3.0.3... IsConnected is returning true with no Wi-Fi/4G connection on Lumia 650 Win10 devices. Can you please re-open and investigate this issue?

**Comment by Ali-Russell** [comment]
Hi, I work with Durai and Helen and tried debugging the plugin src in a sample app.  This issue looks related to the VPN settings on the Win 10 mobile, rather than the device model.

I can see that IsConnected returns true when there is no connection but VPN was connected prior to the connection dropping.  For some reason the Win 10 ConnectionProfile is not updated when the connection drops and the NetworkConnectivityLevel is still InternetAccess.   

Not sure if there is a way to force a network refresh in Win 10 or detect whether the connection is a VPN connection.

**Comment by AlexanderYashyn** [comment]
Had exactly the same problem. Found out that VPN was enabled on the test device
